# Generated by Django 4.2.7 on 2026-02-17 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RectifierData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('site_name', models.CharField(default='', max_length=255)),
                ('project_id', models.CharField(default='', max_length=255)),
                ('ladder', models.CharField(default='', max_length=100)),
                ('sla', models.CharField(default='', max_length=100)),
                ('status_realtime', models.CharField(default='Normal', max_length=50)),
                ('status_ladder', models.CharField(default='Normal', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('door_cabinet', models.CharField(default='Close', max_length=20)),
                ('battery_stolen', models.CharField(default='Close', max_length=20)),
                ('temperature', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('vac_input_l1', models.FloatField(default=0)),
                ('vac_input_l2', models.FloatField(default=0)),
                ('vac_input_l3', models.FloatField(blank=True, null=True)),
                ('vdc_output', models.FloatField(default=0)),
                ('battery_current', models.FloatField(default=0)),
                ('iac_input_l1', models.FloatField(blank=True, null=True)),
                ('iac_input_l2', models.FloatField(blank=True, null=True)),
                ('iac_input_l3', models.FloatField(blank=True, null=True)),
                ('load_current', models.FloatField(default=0)),
                ('load_power', models.FloatField(default=0)),
                ('pac_load_l1', models.FloatField(default=0)),
                ('pac_load_l2', models.FloatField(default=0)),
                ('pac_load_l3', models.FloatField(default=0)),
                ('rectifier_current', models.FloatField(default=0)),
                ('total_power', models.FloatField(default=0)),
                ('battery_bank_1_voltage', models.FloatField(default=0)),
                ('battery_bank_1_current', models.FloatField(default=0)),
                ('battery_bank_1_soc', models.FloatField(default=100)),
                ('battery_bank_1_soh', models.FloatField(default=100)),
                ('battery_bank_2_voltage', models.FloatField(default=0)),
                ('battery_bank_2_current', models.FloatField(default=0)),
                ('battery_bank_2_soc', models.FloatField(default=100)),
                ('battery_bank_2_soh', models.FloatField(default=100)),
                ('battery_bank_3_voltage', models.FloatField(default=0)),
                ('battery_bank_3_current', models.FloatField(default=0)),
                ('battery_bank_3_soc', models.FloatField(default=100)),
                ('battery_bank_3_soh', models.FloatField(default=100)),
                ('backup_duration', models.IntegerField(blank=True, null=True)),
                ('time_remaining', models.IntegerField(blank=True, null=True)),
                ('battery_status', models.CharField(default='Standby', max_length=50)),
                ('start_backup', models.CharField(default='No data', max_length=100)),
                ('soc_avg', models.FloatField(default=100)),
                ('modules_status', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='monitor_rec_timesta_8460ec_idx'), models.Index(fields=['-created_at'], name='monitor_rec_created_9e0bf8_idx')],
            },
        ),
    ]
